@echo ON
setlocal enabledelayedexpansion

set "CMAKE_ARGS=%CMAKE_ARGS% -DBUILD_STATIC_LIBS=OFF"
set "CMAKE_ARGS=%CMAKE_ARGS% -DBUILD_SHARED_LIBS=ON"
set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_SKIP_RPATH=ON"
set "CMAKE_ARGS=%CMAKE_ARGS% -DLIEF_EXAMPLES=OFF"
set "CMAKE_ARGS=%CMAKE_ARGS% -DLIEF_OPT_NLOHMANN_JSON_EXTERNAL=ON"
set "CMAKE_ARGS=%CMAKE_ARGS% -DLIEF_PYTHON_API=OFF"
set "CMAKE_ARGS=%CMAKE_ARGS% -DLIEF_INSTALL_PYTHON=OFF"
set "CMAKE_ARGS=%CMAKE_ARGS% -DLIEF_EXTERNAL_PYBIND11=ON"

set CC=cl.exe
set CXX=cl.exe

mkdir build

cmake %CMAKE_ARGS% -LAH -G "Ninja" -B build  ^
    -DCMAKE_CXX_FLAGS="%CXXFLAGS% /EHsc /wd4359"  ^
    -DCMAKE_C_FLAGS="%CFLAGS% /EHsc /wd4359"  ^
    -DCMAKE_VERBOSE_MAKEFILE=ON  ^
    -DCMAKE_C_USE_RESPONSE_FILE_FOR_OBJECTS=OFF

if %errorlevel% neq 0 exit /b 1
