{% set version = "0.13.2" %}

package:
  name: lief
  version: {{ version }}

source:
  - url: https://github.com/lief-project/LIEF/archive/{{ version }}.tar.gz
    sha256: c68ef94ee613c6557faccc135bdaba4322c2e044be2b806ceea1de763cc099cf
    patches:
      - patches/0001-Call-the-C-DLL-libLIEF.dll-so-it-does-not-clash-with.patch
      - patches/0002-Add-LIEFOptions-for-BUILD_STATIC_LIBS-and-BUILD_SHAR.patch
      - patches/0003-Add-boost-throw_exception-implementation.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ccache
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config            # [not win]
    - patch  # [not win]
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
    - cmake
    - ninja
  host:
    - nlohmann_json

outputs:
  - name: py-lief
    script: install-py-lief.sh  # [unix]
    script: install-py-lief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('py-lief', max_pin='x.x') }}
      ignore_run_exports:
        - python
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config            # [not win]
        # When making a debug build on Windows, we need to patch CMake downloaded pybind11. Sorry.
        - m2-patch  # [win]
        - m2-gcc-libs  # [win]
        - cmake
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
        - setuptools
        - pip
        - pybind11
        - nlohmann_json
      run:
        - {{ pin_subpackage('liblief', exact=True) }}
        - python
    test:
      requires:
        - {{ compiler('cxx') }}
      imports:
        - lief

  - name: liblief
    script: install-liblief.sh  # [unix]
    script: install-liblief.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('liblief', max_pin='x.x') }}
    requirements:
      build:
        - ccache
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - pkg-config            # [not win]
        - cmake
        - ninja
      host:
        - nlohmann_json
    test:
      files:
        - tests
      script: run_test_liblief.sh
      requires:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja

about:
  home: https://lief.quarkslab.com/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: A cross platform library to parse, modify and abstract ELF, PE and MachO formats.
  description: |
    It turns out that many projects need to parse executable formats and they usually re-implement
    their own parser. Moreover these parsers are usually bound to one language.
    LIEF attempts to fill this void.
  doc_url: https://lief.quarkslab.com/doc/stable/index.html
  doc_source_url: https://github.com/lief-project/LIEF/tree/master/doc

extra:
  recipe-maintainers:
    - isuruf
    - msarahan
    - xhochy
    - wolfv
