travis:
  secure:
    BINSTAR_TOKEN: JF/kRet/6tSo9A9Ij2XHbMCctHT0CqSoLV5e6ZthiFvDfSXigiZh4G3JQo1NccHw5RjJl7KYkr5toqPETl20vQwPUaQ+kEPTc2n0mCmFbaCMcT9gKv//Z8KQD8lYqDLzUFQCu41qkbcl5XUJ3nZeOQZ8OLcjkORY63WwuKLNtEckelRkXwdbVAumRBnqGzNtIXLVC/SHrRNt6YY6Pk+/N2UqWgApdo0izLyPEVxJgsWgscuK8KFFvyxaTQIbdGqDTVAjQfDc6OLlsV09cIgFV7j529BhrIp6sQx2WqZMEo3SMPSsCRIunbSFxAmbxnpuMtHk6MNki2WVmpR14l5zUDcwESF16EeiRHF3dvcEtpRC2JhVv7tcmstRi8v0S++EXXxBDphYxtgzQXQA2r0ijlMh3i8E6llmCNpkob/Qlyczk25FlrD2a4CgNjCW2D3Si1WJHFnbF8bW/IJNnuNoGJhNIHvtB2pEnvqADGaWEcPlUOMR6ugblmtFBxycZ6sEt5tRxVum8pLtYihYAK8AjXxkek6eM5aJ1Uo/VpFQuFiasmW36r3ulbTXZXnnbOvRf4G32w4c36ksYM2yC0UQ/DSs9MHuRgrIeo2gIeOX+H9Vc3Aw9LjH5Tek1w1H7dyBa5zUE9DiAKU+7q8f2s+lchibz+K2QMX6Eop3eUAeqgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

provider:
  linux_ppc64le: azure
  linux_aarch64: default
conda_forge_output_validation: true
